name: Azure Key Vault Secret Retrieval

on:
  workflow_dispatch:
    inputs:
      secretName:
        description: 'Name of the secret in Azure Key Vault'
        required: true
        default: 'gh-pr-secret-value' # Set Secret Name Here
      keyVaultName:
          description: 'Name of the Azure Key Vault'
          required: true
          default: '<gh-pr-key-vault' # Set Key Vault Name Here

permissions:
  id-token: write
  contents: read

jobs:
  retrieve-secret:
    runs-on: gh-private-runner-demo #Set Private Runner Here

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Retrieve secret from Azure Key Vault
        run: |
          secretValue=$(az keyvault secret show --name ${{ github.event.inputs.secretName }} --vault-name ${{ github.event.inputs.keyVaultName }} --query value -o tsv)
          echo "SECRET_VALUE=$secretValue" >> $GITHUB_ENV

      - name: Display the secret (for demonstration only)
        run: echo "The secret is $SECRET_VALUE"
